project_id = "oogmuakyqadpynnrasnd"

[functions.dropbox-sync]
verify_jwt = false

[functions.ocr-passport]
verify_jwt = false

[functions.generate-poa]
verify_jwt = false

[functions.check-password-breach]
verify_jwt = false

[functions.ai-agent]
verify_jwt = false