project_id = "oogmuakyqadpynnrasnd"

[functions.inspect-citizenship]
verify_jwt = false

[functions.rename-pdf-fields]
verify_jwt = false

[functions.dropbox-sync]
verify_jwt = false

[functions.ocr-passport]
verify_jwt = false

[functions.ocr-historical]
verify_jwt = false

[functions.ocr-document]
verify_jwt = false

[functions.ocr-wsc-letter]
verify_jwt = false

[functions.ai-translate]
verify_jwt = false

[functions.generate-poa]
verify_jwt = false

[functions.fill-pdf]
verify_jwt = false

[functions.check-password-breach]
verify_jwt = false

[functions.ai-agent]
verify_jwt = false

[functions.client-guide-agent]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.realtime-token]
verify_jwt = false

[functions.analyze-forms]
verify_jwt = false

[functions.get-form-code]
verify_jwt = false

[functions.dropbox-diag]
verify_jwt = false

[functions.dropbox-migration-scan]
verify_jwt = false

[functions.validate-intake-token]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.partner-api]
verify_jwt = false
